version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github_actions"
    directory: "/"
    schedule:
      interval: "weekly"
